#!/bin/sh /etc/rc.common
###########################################
# NOTE - this is an old style init script #
###########################################
 
START=80
APP=comiot
PID_FILE=/var/run/$APP.pid
  
start() {
	start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}
					 
stop() {
	start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
	rm -rf $PID_FILE
}
